### ISSUE TITLE
alchemical_introduction. Improve clarity of instructions

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#10]
In section [3.1.3](https://github.com/michellab/bssccpbiosim2022/blob/main/introduction_to_alchemistry/alchemical_introduction.ipynb)  the sentence ''Hint: look at the engine keyword of FreeEnergy.Relative(). You might also want to change the working directory.'' lacks clarity. How are the delegates meant to look at the API from the Jupyter notebook, or to navigate to different folders and inspect the contents.  More prompting is desirable to minimise the number of delegates who will need help to complete the exercise.

**Comment by annamherz** [comment]
okay, changed!
