### ISSUE TITLE
alchemical_introduction section 5.1 RBFE between pairs of ligands

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#11]
When using the alchemlyb library as the method, this should take about one minute to run.
--> highlight in bold **one minute to run**

''and the MBAR error is'' --> ''and the MBAR statistical uncertainty estimate is''
Have we established exactly how that uncertainty is calculated with alchemlyb ? Propagated 1 standard deviation of each free energy changes between neighboring windows? 

![image](https://user-images.githubusercontent.com/11722212/189609839-5bad14af-dedb-4150-9bb8-b3e5e2a85d45.png)

When the above code is run the resulting uncertainty estimate for the RBFE (0.0847 kcal/mol) is not sqrt ( 0.0471^2 + 0.0499^2)

**Comment by annamherz** [comment]
`BSS.FreeEnergy.Relative.difference` calculates the propagated error as 
```   
        # Propagate the errors. (These add in quadrature.)

        # Measure.
        error0 = _math.sqrt((pmf[-1][2].value() * pmf[-1][2].value()) +
                            (pmf[0][2].value() * pmf[0][2].value()))

        # Reference.
        error1 = _math.sqrt((pmf_ref[-1][2].value() * pmf_ref[-1][2].value()) +
                            (pmf_ref[0][2].value() * pmf_ref[0][2].value()))

        # Error for free-energy difference.
        error = _math.sqrt((error0 * error0) + (error1 * error1)
                           ) * _Units.Energy.kcal_per_mol

```

regardless of whether alchemlyb or the native analysis is used. This takes the MBAR statistical uncertainty from either the native/alchemlyb output at the first and last lambda window. This was already present like this in BSS before the alchemlyb analysis was added.

**Comment by jmichel80** [comment]
This doesn't look consistent with what the output the cell actually reports for the 'alchemlyb' method. The 'native' analysis method does propagage correctly uncertainties. 

![image](https://user-images.githubusercontent.com/11722212/189674596-99148644-10e8-44fb-9357-e0581d7f0135.png)

where 

```
>>> sqrt (0.0471**2+ 0.0499**2)
0.06861792768657474
>>> sqrt (0.1011**2+ 0.1487**2)
0.1798135145087821

```
there must be something inconsistent between the parsing of the outputs generated by the two methodologies.

**Comment by annamherz** [comment]
I think it is parsing the outputs correctly, but the difference is that the MBAR statistical uncertainty calculated at lambda = 0 is not 0 for the alchemlyb method:

```
#pmf_bound
[(0.0, 0.0000e+00 kcal/mol, 0.0423 kcal/mol), (0.125, -3.3943 kcal/mol, 0.0000e+00 kcal/mol), (0.25, -4.0164 kcal/mol, 0.0233 kcal/mol), (0.375, -3.3928 kcal/mol, 0.0293 kcal/mol), (0.5, -2.4648 kcal/mol, 0.0341 kcal/mol), (0.625, -1.5327 kcal/mol, 0.0385 kcal/mol), (0.75, -0.6110 kcal/mol, 0.0424 kcal/mol), (0.875, 0.4121 kcal/mol, 0.0462 kcal/mol), (1.0, 1.5612 kcal/mol, 0.0499 kcal/mol)]
#pmf_free
[(0.0, 0.0000e+00 kcal/mol, 0.0260 kcal/mol), (0.125, -2.3886 kcal/mol, 0.0000e+00 kcal/mol), (0.25, -2.7642 kcal/mol, 0.0178 kcal/mol), (0.375, -2.2310 kcal/mol, 0.0248 kcal/mol), (0.5, -1.4408 kcal/mol, 0.0301 kcal/mol), (0.625, -0.6087 kcal/mol, 0.0347 kcal/mol), (0.75, 0.2661 kcal/mol, 0.0391 kcal/mol), (0.875, 1.2273 kcal/mol, 0.0432 kcal/mol), (1.0, 2.3891 kcal/mol, 0.0471 kcal/mol)]
```
 therefore this error is included in the (`(pmf[0][2].value() * pmf[0][2].value()`) during the difference calculation (as the difference itself is calculated using 
`free_energy = (pmf[-1][1] - pmf[0][1]) - (pmf_ref[-1][1] - pmf_ref[0][1])`
so the error at lambda=0 is propagated as well for error0 and error1, then together for error.
```
>>> sqrt(_math.sqrt(0.0423**2+0.0499**2)**2 + _math.sqrt(0.0260**2+0.0471**2)**2)
0.08469775675896027
```
The error reported during
```
print(f"pmf_free is: {pmf_free[-1][1]} and the MBAR statistical uncertainty is {pmf_free[-1][2]} .")
print(f"pmf_bound is: {pmf_bound[-1][1]} and the MBAR statistical uncertainty is {pmf_bound[-1][2]} .")
```
Is only the cumulative error at the final lambda window, but is not the only value used during the overall error calculation for the difference.

The error for the native method at lambda=0 is 0, so the final error in that case ends up just being `sqrt(bound_error**2 + free_error**2)`.
