### ISSUE TITLE
setup_RBFE plotting the network

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#14]
Is it possible to modify the plotting settings to create a higher resolution version of this figure ? Or to allow users to download a high res pic from the notebook and visualise with another software ? 

![image](https://user-images.githubusercontent.com/11722212/189617981-9f25f210-b9c9-47e0-b1be-f5589e85da92.png)

**Comment by lohedges** [comment]
Yes, that should be possible. As you can imagine, it's hard to choose default parameters that look good for an arbitrary network. I believe that the image is already written to the working directory under `work_dir/images/network.png`. Jenke did optimise a few settings, e.g. DPI, for the saved figure to make sure that it looked okay. (I think it is better than the embedded version.)

Maybe try playing around with some of the settings in [this block](https://github.com/michellab/BioSimSpace/blob/082f4433a0f77fcecb3696d4b8a3708c9bd32332/python/BioSimSpace/Align/_align.py#L488) and let me know if anything gives an improvement.

**Comment by annamherz** [comment]
I've added the work_dir to the plotting, so now it will also saves the image and workshop participants will be able to look at it like that.

> Maybe try playing around with some of the settings in [this block](https://github.com/michellab/BioSimSpace/blob/082f4433a0f77fcecb3696d4b8a3708c9bd32332/python/BioSimSpace/Align/_align.py#L488) and let me know if anything gives an improvement.

I think the resolution of the saved figure is already good! I think it's best to just look at it outside of jupyter notebooks.

**Comment by lohedges** [comment]
Great. Do let me know if you have ideas for improvements. It was a feature that was cobbled together for a previous workshop and hasn't been improved since. As mentioned, it's hard to make something that works well for all systems.
