### ISSUE TITLE
setup RBFE exercises on editing netwok topologies

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#15]
The exercises at the end of section 1.2 could be restructured. At the moment the users have no way of verifying that what they have done is correct, or is leading to an actual change in the networks. 

Ideally the network would be plotted against after a modification. 
At the moment this may not be easy to do with BioSimSpace since network generation and plotting are part of the same function. 

`BSS.Align.generateNetwork(ligands, plot_network=True, names=ligand_names)`

Can we add to the tutorial code to allow simple visualisation of graphs using networkx/matplotlib functionality ? See e.g. 

`https://networkx.org/documentation/stable/reference/drawing.html`

Longer term we could consider decoupling network generation and plotting from BSS.Align but I don't suggest we do this now as it may be tricky to achieve high quality visualisations.

**Comment by annamherz** [comment]
It can now display the adjusted network like this:
![adjusted_network](https://user-images.githubusercontent.com/83006586/190169375-02f1dd95-b1e4-4d90-9e3e-36a45ffe57e6.png)

**Comment by jmichel80** [comment]
Good job !
