### ISSUE TITLE
setup_ABFE ValueError

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#17]
In 2.6 the API call must be updated

![image](https://user-images.githubusercontent.com/11722212/189641930-99ce94d4-70bb-488c-b521-2e9382c4149f.png)

**Comment by fjclark** [comment]
I've [fixed this](https://github.com/michellab/BioSimSpace/commit/f0440ff17f76b25c4423a7ace101985965cff033).
