### ISSUE TITLE
workshop footprint

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#8]
The current version of the workshop after a fresh checkout has ~6.1 GB of data. 

```
(base) julien@julien-QEMU-Virtual-Machine:~/Desktop/bssccpbiosim2022$ du -sch *
5.7G	absolute_binding_free_energies
4.0K	freenrgworkflows
166M	introduction_to_alchemistry
36K	LICENSE
4.0K	README.md
233M	relative_binding_free_energies
6.1G	total
(base) julien@julien-QEMU-Virtual-Machine:~/Desktop/bssccpbiosim2022$ 
```

Do we absolutely need all these ?  
If necessary we could compress the simfile.dat files in the various absolute_binding_free_energies/example_output/*/*/*/output/lambda_*/ folders which should reduce disk usage by a factor of x3.

**Comment by fjclark** [comment]
Hi @jmichel80, they aren't absolutely necessary. I'll change the exercises slightly to allow me to remove all data for the vanish and restrain stages, and compress the simfile.dat files.

**Comment by fjclark** [comment]
Hi @jmichel80 I've compressed all the simfiles and removed all unnecessary output. I've also updated BioSimSpace so that the native analysis with SOMD works with the compressed output. The footprint is now:

```
(base) jovyan@jupyter-ebd6725b-2d6ddb-2d4b92-2d9600-2d887ba76cd96c:~/workshop$ du -sch *
571M    absolute_binding_free_energies
0       freenrgworkflows
166M    introduction_to_alchemistry
36K     LICENSE
4.0K    README.md
233M    relative_binding_free_energies
969M    total
```
